function transferPrintAction(request, response) {
  var monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  var recID = request.getParameter('intid');
  var res = nlapiLoadRecord('transfer',recID);
  var tran_no = res.getFieldValue('transactionnumber');
  var dept = res.getFieldValue('department');
  var tid = res.getFieldValue('tranid');
  var fromaccount = res.getFieldText('fromaccount');
  var toaccount = res.getFieldText('toaccount');
  var frombalance = res.getFieldValue('frombalance');
  var tobalance = res.getFieldValue('tobalance');
  var tran_Date = nlapiStringToDate(res.getFieldValue('trandate'));
  var tDate = tran_Date.getDate()+"-"+monthNames[tran_Date.getMonth()]+"-"+tran_Date.getFullYear();
  var from_cur = res.getFieldValue('fromcurrencyname');
  var to_cur = res.getFieldValue('tocurrencyname');
  var exhrate = res.getFieldValue('exchangerate');
  var fromamount = res.getFieldValue('fromamount');
  var toamount = res.getFieldValue('toamount');
  var memo = res.getFieldValue('memo');
  var cls = res.getFieldValue('class');
  var loc = res.getFieldValue('location');
  var subsidiary  = res.getFieldValue('subsidiary');
  var renderer = nlapiCreateTemplateRenderer();
  var template = "";
  template += "<?xml version=\"1.0\"?><!DOCTYPE pdf PUBLIC \"-//big.faceless.org//report\" \"report-1.1.dtd\"> ";
  template += "<pdf> ";
  template += "<head> ";
  template += "   <#if .locale == \"ru_RU\"> ";
  template += "   <link name=\"verdana\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.verdana}\" src-bold=\"${nsfont.verdana_bold}\" bytes=\"2\" /> ";
  template += "   </#if> ";	

  template += '<macrolist>';
  template += '<macro id="nlheader">';
  if(subsidiary == '1'){
    template += '   <table class="header" style="width: 100%;"><tr><td><img src=" https://system.eu2.netsuite.com/core/media/media.nl?id=4662&amp;c=4647359&amp;h=d2eba6d03b2df756f430" style="width:657px; height:120px;" /></td></tr></table>';
  }else{
    template += '<table class="header" style="width: 100%;"><tr><td><img src="https://system.eu2.netsuite.com/core/media/media.nl?id=1542&amp;c=4647359&amp;h=6133025b4814846195e4" style="width:657px; height:130px;" /></td></tr></table>';
  }
  template += '</macro>';

  template += '<macro id="nlfooter">';
    template += '<table class="footer" style="width: 100%;"><tr><td><img src="https://system.eu2.netsuite.com/core/media/media.nl?id=1543&amp;c=4647359&amp;h=90677a0f341bea21aec2" style="width:655px;height:70px;"/></td></tr></table>';
  template += '</macro>';
  template += '</macrolist>';
  template += "   <style type=\"text/css\">table ";
  template += "{      font-family: sans-serif; ";
  template += "      font-size: 10pt; ";  
  template += "      table-layout: fixed; ";
  template += "      } ";
  template += "      th ";
  template += "{      font-weight: bold; ";
  template += "      font-size: 9pt; ";
  template += "      vertical-align: middle; ";
  template += "      padding: 5px 6px 3px; ";
  template += "      background-color: #e3e3e3; ";
  template += "      color: #000000; ";
  template += "      } ";
  template += "      td p { align:left; } ";
  template += "      b ";
  template += "{      font-weight: bold; ";
  template += "      color: #000000; ";
  template += "      } ";
  template += "      table.header td ";
  template += "{      padding: 0; ";
  template += "      font-size: 10pt; ";
  template += "      } ";
  template += "      table.footer td ";
  template += "{      padding: 0; ";
  template += "      font-size: 9pt; ";
  template += "      } ";
  template += "      table.itemtable th ";
  template += "{      padding-bottom: 10px; ";
  template += "      padding-top: 10px; ";
  template += "      } ";
  template += "      table.total ";
  template += "{      page-break-inside: avoid; ";
  template += "      } ";
  template += "      tr.totalrow ";
  template += "{      background-color: #e3e3e3; ";
  template += "      line-height: 200%; ";
  template += "      } ";
  template += "      td.totalboxtop ";
  template += "{      font-size: 13pt; ";
  template += "      background-color: #e3e3e3; ";
  template += "      } ";
  template += "      span.title ";
  template += "{      font-size: 29pt; ";
  template += "      } ";
  template += "      span.number ";
  template += "{      font-size: 17pt; ";
  template += "      } ";
  template += "      span.itemname ";
  template += "{      font-weight: bold; ";
  template += "      line-height: 150%; ";
  template += "      } ";
  template += "      hr ";
  template += "{      width: 100%; ";
  template += "      color: #d3d3d3; ";
  template += "      background-color: #d3d3d3; ";
  template += "      height: 1px; ";
  template += "      } ";
  template += "   </style> ";
  template += "</head>" ;
  template += '<body header="nlheader" header-height="13%" footer="nlfooter" footer-height="7%" padding="0.5in 0.5in 0.5in 0.5in" size="A4">';
  template += '<table style="width:100%;">';
  template += '<tr>';
  template += '<td align="center" style="font-size:16px;font-weight:bold;text-decoration: underline;">Transfer</td>';
  template += '</tr>';
  template += '</table>';
  template += '<table style="width:100%; font-size:12px;">';
  template += '<tr>';
  template += '<td style="width:25%;font-weight:bold;">Transfer #</td><td style="width:34%">'+tid+'</td>';
  template += '<td style="width:15%;font-weight:bold;">Date</td><td style="width:34%">'+tDate+'</td>';
  template += '</tr>';
  if(memo){
  template += '<tr>';
  template += '<td style="width:25%;font-weight:bold;">Memo</td><td style="width:34%">'+relaceCharector(memo)+'</td>';
  template += '</tr>';
  }
  template += '</table>';
  template += '<table style="width:100%;"><tr><td>&nbsp;</td></tr></table>';
  template += '<table style="width:100%;">';
  template += '<tr>';
  template += '<td style="font-weight:bold;font-size:14px;"><u>From Account Details:</u></td>';
  template += '</tr>';
  template += '</table>';
  template += '<table style="width:100%; font-size:12px;">';
  template += '<tr>';
  template += '<td style="width:10%;font-weight:bold;">Account</td><td style="width:1%;">:</td><td style="width:70%">'+relaceCharector(fromaccount)+'</td><td style="width:20%"></td>';
  template += '</tr>';
  template += '<tr>';
  template += '<td style="width:10%;font-weight:bold;">Amount</td><td style="width:1%;">:</td><td style="width:50%">'+fromamount+'</td><td style="width:40%"></td>';
  template += '</tr>';
  template += '<tr>';
  template += '<td style="width:10%;font-weight:bold;">Currency</td><td style="width:1%;">:</td><td style="width:50%">'+from_cur+'</td><td style="width:40%"></td>';
  template += '</tr>';
  /*template += '<tr>';
        template += '<td style="width:15%;font-weight:bold;">Balance</td><td>:</td><td style="width:44%">'+frombalance+'</td>';
		template += '<td style="width:15%;font-weight:bold;">Balance</td><td>:</td><td style="width:44%">'+tobalance+'</td>';
		template += '</tr>';*/
  template += '</table>';
  template += '<table style="width:100%;"><tr><td>&nbsp;</td></tr></table>';
  template += '<table style="width:100%;">';
  template += '<tr>';
  template += '<td style="font-weight:bold;font-size:14px;"><u>To Account Details:</u></td>';
  template += '</tr>';
  template += '</table>';

  template += '<table style="width:100%; font-size:12px;">';

  template += '<tr>';
  template += '<td style="width:10%;font-weight:bold;">Account</td><td style="width:1%;">:</td><td style="width:70%">'+relaceCharector(toaccount)+'</td><td style="width:20%"></td>';
  template += '</tr>';
  template += '<tr>';
  template += '<td style="width:10%;font-weight:bold;">Amount</td><td style="width:1%;">:</td><td style="width:50%">'+toamount+'</td><td style="width:40%"></td>';
  template += '</tr>';
  template += '<tr>';
  template += '<td style="width:10%;font-weight:bold;">Currency</td><td style="width:1%;">:</td><td style="width:50%">'+to_cur+'</td><td style="width:40%"></td>';
  template += '</tr>';
  template += '</table>';
  template += '<table style="width:100%;margin-top:35px;">';
  template += '<tr><td align="left"><b>________________</b><br/><br/><b>Prepared By</b></td><td align="center"><b>________________</b><br/><br/><b>Checked By</b></td><td align="right"><b>________________</b><br/><br/><b>Approved By</b></td></tr>';
  template += '</table>';
  template += '</body>';
  template += '</pdf>';        
  renderer.setTemplate(template);
  renderer.addRecord('record', res);
  var xml = renderer.renderToString();
  var file = nlapiXMLToPDF(xml);
  response.setContentType('PDF', 'Tranfer Funds.pdf','inline');
  response.write(file.getValue());
}
function relaceCharector(charVal) {	
  return charVal.replace(/&/g, "&amp;");	
}
function strReplace(str,replaceVal){
  var res = str.replace(replaceVal, "");
  return res;
}