function printCreditMemoLH(request, response) {
    var invID = request.getParameter("creditmemoID");
    var subsidiary = request.getParameter("subsidiary");
    var invoice = nlapiLoadRecord('creditmemo', invID);
    var renderer = nlapiCreateTemplateRenderer();
    var template = "";
    template += "<?xml version=\"1.0\"?><!DOCTYPE pdf PUBLIC \"-//big.faceless.org//report\" \"report-1.1.dtd\"> ";
    template += "<pdf> ";
    template += "   <head> ";
    template += "      <#";
    template += "if .locale == \"ru_RU\"> ";
    template += "      <link name=\"verdana\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.verdana}\" src-bold=\"${nsfont.verdana_bold}\" bytes=\"2\" /> ";
    template += "      </#if> ";
    template += "      <macrolist> ";
    template += '<macro id="nlheader">';
    template += '<#if record.subsidiary.internalid?string == \'1\'>';
    template += '<table class="header" style="width: 100%; margin-top:-32px;margin-left:-68px; margin-right:-40px;"><tr>';
    template += '<td><img src="https://system.eu2.netsuite.com/core/media/media.nl?id=9211&amp;c=4647359&amp;h=fc2ca0a52e15d8d22d59" style="width:800px; height:120px;" /></td>';
    template += '</tr></table>';
    template += '</#if>';
    template += '<!-- SALLC -->';
    template += '<#if record.subsidiary.internalid?string == \'2\'>  ';

    template += '<table class="header" style="width: 100%; margin-top:-32px;margin-left:-68px; margin-right:-40px;"><tr>';
    template += '<td><img src="https://system.eu2.netsuite.com/core/media/media.nl?id=9196&amp;c=4647359&amp;h=215721097cda3e1e1ad8" style="width:800px; height:120px;" /></td>';
    template += '</tr>';
    template += '</table>';
    template += '</#if>';
    template += ' <#if record.subsidiary.internalid?string == \'8\' && record.location.internalid?string == \'8\'> ';
    template += '           <table class="header" style="width: 100%; margin-top:-48px;margin-left:-50px;"><tr>';
    template += '<td><img src="https://4647359.app.netsuite.com/core/media/media.nl?id=26496&amp;c=4647359&amp;h=21w54VT21qJNaGVHZPaPVTzW9PW2DgyTFourxU2Qxl7fVlb7" style="width:768px; height:140px;" /></td>';
    template += '</tr>';
    template += '</table>';
    template += ' </#if>';

    template += ' <#if record.subsidiary.internalid?string == \'8\' && record.location.internalid?string != \'8\'> ';
    template += '           <table class="header" style="width: 100%; margin-top:-48px;margin-left:-50px;"><tr>';
    template += '<td><img src="https://4647359.app.netsuite.com/core/media/media.nl?id=26488&amp;c=4647359&amp;h=6Uxc0nbUkUIpXGHsPLniGwEfM-PfsyucvPJwV0Vhus-USYG_" style="width:768px; height:140px;" /></td>';
    template += '</tr>';
    template += '</table>';
    template += ' </#if>';

    template += '</macro>';
    template += '<macro id="nlfooter">';
    template += "<#if record.subsidiary.internalid?string == '8'>  ";
    template += '          <table class="footer" border="0" ';
    template += '              style="width: 100%;background-color:#000;margin-top:48px;margin-left :-40px;">';
    template += '              <tr>';
    template += '<td>';
    template += '<img src="https://4647359.app.netsuite.com/core/media/media.nl?id=14615&amp;c=4647359&amp;h=ae717ee9182515bf331e" style="width:758px;height:55%;"/>';

    template += '  </td>';
    template += '  </tr>';
    template += ' </table>';
    template += ' <div style="position:relative;top:-108px;bottom:-92px;left:518px;">';
    template += '               <img src="https://system.eu2.netsuite.com/core/media/media.nl?id=9205&amp;c=4647359&amp;h=7003b6a4832399179079" style="width:100%;height:100%;"/>';
    template += '            </div> ';
    template += '             <#else>';
    template += '              <table class="footer" border="0" ';
    template += '                style="width: 100%; margin-left:-48px; margin-right:-65px; margin-bottom: -255px;background-color:#000;margin-top:40px;">';
    template += '                <tr>';
    template += '                  <td>';
    template += '                <img src="https://system.eu2.netsuite.com/core/media/media.nl?id=9210&amp;c=4647359&amp;h=e6070c9cd462193b9b95" style="width:750px;height:40%;"/>';
    template += '                ';
    template += '                  </td>';
    template += '                </tr>';
    template += ' </table>';
    template += '            <div style="position:relative;top:-266px;bottom:-92px;left:483px;">';
    template += '               <img src="https://system.eu2.netsuite.com/core/media/media.nl?id=9205&amp;c=4647359&amp;h=7003b6a4832399179079" style="width:100%;height:100%;"/>';
    template += '            </div> ';
    template += '            </#if>';
    template += '</macro>';
    template += "      </macrolist> ";
    template += "    <style type=\"text/css\">table ";
    template += "{            font-family: sans-serif; ";
    template += "    		font-family:arial,helvetica,sans-serif; ";
    template += "            font-size: 10pt; ";
    template += "            table-layout: fixed; ";
    template += "        } ";
    template += "        th ";
    template += "{            font-weight: bold; ";
    template += "            font-size: 9pt; ";
    template += "            vertical-align: middle; ";
    template += "            padding: 5px 6px 3px; ";
    template += "            background-color: #e3e3e3; ";
    template += "            color: #000000; ";
    template += "        } ";
    template += "        td p { align:left; } ";
    template += "        /*td { ";
    template += "    padding: 4px 6px; ";
    template += "}*/ ";
    template += "        b ";
    template += "{            font-weight: bold; ";
    template += "            color: #000000; ";
    template += "        } ";
    template += "        table.header td ";
    template += "{            padding: 0px; ";
    template += "            font-size: 10pt; ";
    template += "        } ";
    template += "        table.footer td ";
    template += "{            padding: 0px; ";
    template += "            font-size: 9pt; ";
    template += "        } ";
    template += "        table.itemtable th ";
    template += "{            padding-bottom: 10px; ";
    template += "            padding-top: 10px; ";
    template += "        } ";
    template += "        table.body td ";
    template += "{            padding-top: 2px; ";
    template += "        } ";
    template += "        table.total ";
    template += "{            page-break-inside: avoid; ";
    template += "        } ";
    template += "        tr.totalrow ";
    template += "{            background-color: #e3e3e3; ";
    template += "            line-height: 200%; ";
    template += "        } ";
    template += "        td.totalboxtop ";
    template += "{            font-size: 12pt; ";
    template += "            background-color: #e3e3e3; ";
    template += "        } ";
    template += "        td.addressheader ";
    template += "{            font-size: 8pt; ";
    template += "            padding-top: 6px; ";
    template += "            padding-bottom: 2px; ";
    template += "        } ";
    template += "        td.address ";
    template += "{            padding-top: 0px; ";
    template += "        } ";
    template += "        td.totalboxmid ";
    template += "{            font-size: 28pt; ";
    template += "            padding-top: 20px; ";
    template += "            background-color: #e3e3e3; ";
    template += "        } ";
    template += "        td.totalboxbot ";
    template += "{            background-color: #e3e3e3; ";
    template += "            font-weight: bold; ";
    template += "        } ";
    template += "        span.title ";
    template += "{            font-size: 28pt; ";
    template += "        } ";
    template += "        span.number ";
    template += "{            font-size: 16pt; ";
    template += "        } ";
    template += "        span.itemname ";
    template += "{            font-weight: bold; ";
    template += "            line-height: 150%; ";
    template += "        } ";
    template += "        hr ";
    template += "{            width: 100%; ";
    template += "            color: #d3d3d3; ";
    template += "            background-color: #d3d3d3; ";
    template += "            height: 1px; ";
    template += "        } ";
    template += "</style> ";
    template += "   </head> ";
    template += "   <body header=\"nlheader\" header-height=\"13%\" footer=\"nlfooter\" footer-height=\"8%\" padding=\"0.3in 0.3in 0.3in 0.3in\" size=\"A4\"> ";
    template += "      <table style=\"width::100%;font-size:14px;border:solid 1px #000000;\"> ";
    template += "         <tr> ";
    template += "            <td style=\"width:336px;font-weight:bold;\" align=\"left\">CREDIT NOTE</td> ";
    template += "            <td style=\"width:346px;font-weight:bold;\" align=\"right\">DATE : ${record.trandate?string[\"d-MMM-yyyy\"]}</td> ";
    template += "         </tr> ";
    template += "      </table> ";
    template += "      <table style=\"width: 100%; margin-top: 10px;border:solid 1px #000000;font-size:12px;\"> ";
    template += "         <tr> ";
    template += "            <td style=\"border-right:1px solid black;\" colspan=\"7\" align=\"left\"> ";
    template += "               <table> ";
    template += "                  <tr> ";
    template += "                     <td style=\"font-size:15px;font-weight:bold;\">${record.entity}<br/></td> ";
    template += "                  </tr> ";
    template += "                  <tr> ";
    template += "                     <td>${record.entity.address}<br/></td> ";
    template += "                  </tr> ";
    template += "                  <tr> ";
    template += "                     <td>${record.entity.phone}</td> ";
    template += "                  </tr> ";
    template += "               </table> ";
    template += "            </td> ";
    template += "            <td style=\"border-right:1px solid black;vertical-align:middle;\" colspan=\"4\" align=\"center\"> ";
    template += "               <table> ";
    template += "                  <tr> ";
    template += "                     <td style=\"font-size:16px;font-weight:bold;\">${record.tranid}</td> ";
    template += "                  </tr> ";
    template += "               </table> ";
    template += "            </td> ";
    template += "            <td colspan=\"5\" align=\"left\"> ";
    template += "               <table> ";
    template += "                  <tr> ";
    template += "                     <td><b>LPO No :</b> ${record.otherrefnum}<br/></td> ";
    template += "                  </tr> ";
    template += "                  <tr> ";
    template += "                     <td><b>Pay. Term :</b> ${record.entity.terms}<br/></td> ";
    template += "                  </tr> ";
    template += "                  <tr> ";
    template += "                     <td><b>Pay Due :</b> ${record.duedate}<br/></td> ";
    template += "                  </tr> ";
    template += "                  <tr> ";
    template += "                     <td><b>Sales Rep :</b> ${record.salesrep.entityid} ${record.salesrep.firstname}<br/></td> ";
    template += "                  </tr> ";
    template += "                  <tr> ";
    template += "                     <td><b>Location :</b> ${record.location}<br/></td> ";
    template += "                  </tr> ";
    template += "               </table> ";
    template += "            </td> ";
    template += "         </tr> ";
    template += "      </table> ";
    template += "      <#";
    template += "if record.item?has_content> ";
    template += "      <table class=\"itemtable\" style=\"width: 100%; margin-top: 10px;border:1px solid #000000;\"> ";
    template += "         <!-- start items --><#list record.item as item><#if item_index==0> ";
    template += "         <thead> ";
    template += "            <tr style=\"line-height:180%;\"> ";
    template += "               <td align=\"center\" colspan=\"6\" style=\"border-bottom:solid 1px #000000;font-weight:bold;\">Item</td> ";
    template += "               <td align=\"center\" colspan=\"12\"  style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Job Description</td> ";
    template += "               <td align=\"center\" colspan=\"4\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Quantity</td> ";
    template += "               <td align=\"center\" colspan=\"4\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Unit Price</td> ";
    template += "               <td align=\"center\" colspan=\"5\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Amount(${record.currencysymbol})</td> ";
    template += "            </tr> ";
    template += "         </thead> ";
    template += "         </#if> ";
    template += "         <tr style=\"line-height:200%;\"> ";
    template += "            <#assign rescode = 0/> ";
    template += "            <td align=\"center\" colspan=\"6\" valign=\"justify\">${item.item}</td> ";
    template += "            <td align=\"center\" colspan=\"12\" valign=\"justify\" style=\"border-left:solid 1px #000000;\">${item.description}</td> ";
    template += "            <td align=\"center\" colspan=\"4\" valign=\"justify\" style=\"border-left:solid 1px #000000;\">${item.quantity}</td> ";
    template += "            <td align=\"right\" colspan=\"4\" valign=\"justify\" style=\"border-left:solid 1px #000000;\">${item.rate?string[\"#,##0.00\"]}</td> ";
    template += "            <td align=\"right\" colspan=\"5\" valign=\"justify\" style=\"padding:5px;border-left:solid 1px #000000;\">${item.amount?string[\"#,##0.00\"]}</td> ";
    template += "         </tr> ";
    template += "         </#list><!-- end items --> ";
    template += "         <tr style=\"line-height:180%;\"> ";
    template += "            <td align =\"right\" colspan=\"26\" style=\"padding:5px;border-top:solid 1px #000000;\">Tax Total</td> ";
    template += "            <td align=\"right\" colspan=\"5\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\">${record.taxtotal?string[\"#,##0.00\"]}</td> ";
    template += "         </tr> ";
    template += "         <tr style=\"line-height:180%;\"> ";
    template += "            <td align =\"left\" colspan=\"26\" style=\"padding:5px;border-top:solid 1px #000000;\"><b>Amount in words: </b><i><b>${record.currencysymbol}</b><b>&nbsp;${record.custbody_amount_into_words?capitalize}</b></i></td> ";
    template += "            <td align=\"right\" colspan=\"5\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\"><b>${record.total?string[\"#,##0.00\"]}</b></td> ";
    template += "         </tr> ";
    template += "      </table> ";
    template += "      <table style=\"width:100%;\"> ";
    template += "         <tr> ";
    template += "            <td align=\"right\"><b>E. &#38;";
    template += "O.E.</b></td> ";
    template += "         </tr> ";
    template += "      </table> ";
    template += "      </#";
    template += "if> ";
    template += "      <table style=\"margin-top:10px;width:100%;\"> ";
    template += "         <tr> ";
    template += "            <td style=\"font-weight:bold;padding-right :20px;\" align=\"right\">For ${record.subsidiary.legalname}</td> ";
    template += "         </tr> ";
    template += "      </table> ";
    template += "      <table style=\"margin-top:10px;\"> ";
    template += "         <tr> ";
    template += "            <td style=\"width:75px;margin-top:5px;\" align=\"left\">Received By</td> ";
    template += "            <td style=\"width:100px;margin-top:5px;\" align=\"left\"> : _________________________________</td> ";
    template += "         </tr> ";
    template += "         <tr> ";
    template += "            <td style=\"width:75px;margin-top:5px;\" align=\"left\">Received Date</td> ";
    template += "            <td style=\"width:100px;margin-top:5px;\" align=\"left\"> : _________________________________</td> ";
    template += "         </tr> ";
    template += "      </table> ";
    template += "      <table style=\"width:100%;\"> ";
    template += "         <tr> ";
    template += "            <td colspan=\"3\" style=\"font-size:10px;\"><br /><br /></td> ";
    template += "            <td><b>______________</b><br/>Prepared by</td> ";
    template += "            <td><b>______________</b><br/>Approved by</td> ";
    template += "         </tr> ";
    template += "      </table> ";
    template += "   </body> ";
    template += "</pdf>";
    renderer.setTemplate(template);
    renderer.addRecord('record', invoice);
    var xml = renderer.renderToString();
    var file = nlapiXMLToPDF(xml);
    response.setContentType('PDF', 'CreditMemo' + invoice.getFieldValue("id") + '.pdf', 'inline');
    response.write(file.getValue());
}