function printInvoiceArabic(request,response){
  var invID = request.getParameter("creditmemoID");
  var file = nlapiPrintRecord('TRANSACTION', invID, 'PDF', {formnumber: '131'});

  response.setContentType('PDF', 'creditmemo_'+invID+'.pdf', 'INLINE');

  response.write(file.getValue());
  /*var invID = request.getParameter("invoiceID");
  var subsidiary = request.getParameter("subsidiary");
  var invoice = nlapiLoadRecord('invoice', invID);
  var renderer = nlapiCreateTemplateRenderer();
  var template = "";
  template += "<?xml version=\"1.0\"?><!DOCTYPE pdf PUBLIC \"-//big.faceless.org//report\" \"report-1.1.dtd\"> ";
  template += "<pdf> ";
  template += "<head> ";
  template += "<#" ;
  template += "if .locale == \"ru_RU\"> ";
  template += "    <link name=\"verdana\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.verdana}\" src-bold=\"${nsfont.verdana_bold}\" bytes=\"2\" /> ";
  template += "</#if> ";
  template += "    <macrolist> ";
  template += "        <macro id=\"nlheader\"> ";
  template += "            <table class=\"header\" style=\"width: 100%;\"></table> ";
  template += "          <table style=\"height:35%;\"> ";
  template += "            <tr><td>&nbsp;" ;
  template += "</td></tr> ";
  template += "          </table> ";
  template += "             <table style=\"width:100%;margin-top:0.5px;font-size:10px;font-weight:bold;border-left:solid 1px #000000;border-top:solid 1px #000000;border-right:solid 1px #000000;\"> ";
  template += "            <tr><td style=\"width:255px;border-right:solid 1px #000000;\">Bill To :</td><td style=\"width:80px;\">&nbsp;" ;
  template += "</td></tr> ";
  template += "            </table> ";
  template += "             <table style=\"width:100%;font-size:16px;border-left:solid 1px #000000;border-right:solid 1px #000000;margin-top:0.1px;\"> ";
  template += "<#if record.entity.custentity_cr_number?has_content>";
  template += "<tr><#if record.custbody_legal_entity?has_content><td style=\"width:342px;font-weight:bold;\" align=\"left\">${record.custbody_legal_entity}</td><#else><td style=\"width:342px;font-weight:bold;\" align=\"left\">${record.entity.custentity_customer_name}</td></#if><td style=\"width:22px;font-weight:bold;font-size:14px;border-left:solid 1px #000000;\" align=\"right\">Invoice No : </td><td style=\"width:60px;font-weight:bold;font-size:14px;\" align=\"right\">${record.tranid}</td></tr>";
  template += "<tr><td style=\"width:342px;font-weight:bold;font-size:12px;\" align=\"left\">CR No : ${record.entity.custentity_cr_number}<br/>VAT No : ${record.entity.vatregnumber}</td><td style=\"width:22px;font-weight:bold;font-size:14px;border-left:solid 1px #000000;\" align=\"right\">Invoice Date : </td><td style=\"width:60px;font-weight:bold;font-size:14px;\" align=\"right\">${record.trandate?string[\"d-MMM-yyyy\"]}</td></tr>";
  template += "<tr><td style=\"width:342px;font-weight:bold;font-size:9px;\" align=\"left\">${record.entity.address}</td><td style=\"width:22px;font-weight:bold;font-size:14px;border-left:solid 1px #000000;\" align=\"right\">Alfaris VAT No :</td><td style=\"width:60px;font-weight:bold;font-size:14px;\" align=\"right\"> ${record.custbody_trn}</td></tr>";
  template += "<#else>";
  template += "<tr><#if record.custbody_legal_entity?has_content><td style=\"width:342px;font-weight:bold;\" align=\"left\">${record.custbody_legal_entity}</td><#else><td style=\"width:342px;font-weight:bold;\" align=\"left\">${record.entity.custentity_customer_name}</td></#if><td style=\"width:22px;font-weight:bold;font-size:14px;border-left:solid 1px #000000;\" align=\"right\">Invoice No : </td><td style=\"width:60px;font-weight:bold;font-size:14px;\" align=\"right\">${record.tranid}</td></tr>";
  template += "<tr><td style=\"width:342px;font-weight:bold;font-size:12px;\" align=\"left\">VAT No : ${record.entity.vatregnumber}</td><td style=\"width:22px;font-weight:bold;font-size:14px;border-left:solid 1px #000000;\" align=\"right\">Invoice Date : </td><td style=\"width:60px;font-weight:bold;font-size:14px;\" align=\"right\">${record.trandate?string[\"d-MMM-yyyy\"]}</td></tr>";
  template += "<tr><td style=\"width:342px;font-weight:bold;font-size:9px;\" align=\"left\">${record.entity.address}</td><td style=\"width:22px;font-weight:bold;font-size:14px;border-left:solid 1px #000000;\" align=\"right\">Alfaris VAT No : </td><td style=\"width:60px;font-weight:bold;font-size:14px;\" align=\"right\">${record.custbody_trn}</td></tr>";
  template += "</#if>";
  template += "            </table> ";
  template += "          <table style=\"width:100%;margin-top:0.5px;font-size:10px;\"> ";
  template += "    	<tr> ";
  template += "      	<td style=\"border-left:solid 1px #000000;border-top:solid 1px #000000;border-bottom:solid 1px #000000;\"> ";
  template += "          <table> ";
  template += "          <tr><td><b>Tel No : </b> ${record.entity.phone}</td></tr> ";
  template += "          <tr><td><b>Fax No : </b> ${record.entity.fax}</td></tr> ";
  template += "          <tr><td><b>Attn : </b> ${record.custbody_attention}</td></tr> ";
  template += "          <tr><td><b>Contract : </b> <#if record.custbody_customer_doc_ref_no?has_content>${record.custbody_customer_doc_ref_no}<#else>${record.custbody_invoice_qt_number_cf}</#if></td></tr> ";
  template += "          <#if record.custbody_po_number_of_so?has_content><tr><td><b>LPO No : </b> ${record.custbody_po_number_of_so}</td></tr><#else><tr><td><b>LPO No : </b> ${record.otherrefnum}</td></tr></#if> ";
  template += "          </table> ";
  template += "      </td> ";
  template += "          <td style=\"border-left:solid 1px #000000;border-top:solid 1px #000000;border-bottom:solid 1px #000000;\"> ";
  template += "         <table> ";
  template += "         <tr><td><b>Pay Terms : </b>  ${record.custbody_payment_terms}</td></tr> ";
  template += "         <#if record.duedate?string == \"\"> ";
  template += "         <tr><td><b>Pay Due :</b> ${record.duedate}</td></tr> ";
  template += "         <#else><tr><td><b>Pay Due : </b> ${record.duedate?string[\"d-MMM-yyyy\"]}</td></tr> ";
  template += "         </#if> ";
  template += "         <tr><td><b>Sales Rep : </b> ${record.salesrep.entityid} ${record.salesrep.firstname}</td></tr> ";
  template += "         <tr><td><b>Site : </b> ${record.custbody_site}</td></tr> ";
  template += "         </table> ";
  template += "         </td> ";
  template += "         <td style=\"border-left:solid 1px #000000;border-top:solid 1px #000000;border-bottom:solid 1px #000000;border-right:solid 1px #000000;width:259px;\"> ";
  template += "         <#if record.custbody_bank_details?has_content><span>${record.custbody_bank_details}</span></#if> ";
  template += "         <br/> ";
  template += "        <b style=\"font-size:10px;\">All bank transfer charges to be borne by customer</b> ";
  template += "      </td> ";
  template += "      </tr></table> ";
  template += "          <table style=\"width:100%;font-size:13px;\"> ";
  template += "            <tr><td style=\"width:14%;\"><b>Scope of work</b></td><td style=\"width:1%;\"><b>:</b></td><td style=\"width:85%;\">${record.custbody_scope_of_work}</td></tr> ";
  template += "          </table> ";
  template += "        	</macro> ";
  template += "        	<macro id=\"nlfooter\"> ";
  template += "            <table class=\"footer\" style=\"width: 100%;\"> ";
  template += "            <!--<tr> ";
  template += "        	<td><img src=\"https://system.eu2.netsuite.com/core/media/media.nl?id=1543&amp;c=4647359&amp;h=90677a0f341bea21aec2\" style=\"width:655px;height:70px;\"/></td> ";
  template += "	    	</tr>--> ";
  template += "            <tr><td align=\"left\" style=\"width:75%;\">&nbsp;" ;
  template += "</td><td align=\"right\">&nbsp;" ;
  template += "( Page <pagenumber/> of <totalpages/> )</td></tr> ";
  template += "            </table> ";
  template += "        	</macro> ";
  template += "    </macrolist> ";
  template += "    <style type=\"text/css\">table ";
  template += "{            font-family: sans-serif; ";
  template += "    		font-family:arial,helvetica,sans-serif; ";
  template += "            font-size: 10pt; ";
  template += "            table-layout: fixed; ";
  template += "        } ";
  template += "        th ";
  template += "{            font-weight: bold; ";
  template += "            font-size: 9pt; ";
  template += "            vertical-align: middle; ";
  template += "            padding: 5px 6px 3px; ";
  template += "            background-color: #e3e3e3; ";
  template += "            color: #000000; ";
  template += "        } ";
  template += "        td p { align:left; } ";
  template += "        /*td { ";
  template += "    padding: 4px 6px; ";
  template += "} ";
  template += "        b ";
  template += "{            font-weight: bold; ";
  template += "            color: #000000; ";
  template += "        } ";
  template += "        table.header td ";
  template += "{            padding: 0px; ";
  template += "            font-size: 10pt; ";
  template += "        } ";
  template += "        table.footer td ";
  template += "{            padding: 0px; ";
  template += "            font-size: 9pt; ";
  template += "        } ";
  template += "        table.itemtable th ";
  template += "{            padding-bottom: 10px; ";
  template += "            padding-top: 10px; ";
  template += "        } ";
  template += "        table.body td ";
  template += "{            padding-top: 2px; ";
  template += "        } ";
  template += "        table.total ";
  template += "{            page-break-inside: avoid; ";
  template += "        } ";
  template += "        tr.totalrow ";
  template += "{            background-color: #e3e3e3; ";
  template += "            line-height: 200%; ";
  template += "        } ";
  template += "        td.totalboxtop ";
  template += "{            font-size: 12pt; ";
  template += "            background-color: #e3e3e3; ";
  template += "        } ";
  template += "        td.addressheader ";
  template += "{            font-size: 8pt; ";
  template += "            padding-top: 6px; ";
  template += "            padding-bottom: 2px; ";
  template += "        } ";
  template += "        td.address ";
  template += "{            padding-top: 0px; ";
  template += "        } ";
  template += "        td.totalboxmid ";
  template += "{            font-size: 28pt; ";
  template += "            padding-top: 20px; ";
  template += "            background-color: #e3e3e3; ";
  template += "        } ";
  template += "        td.totalboxbot ";
  template += "{            background-color: #e3e3e3; ";
  template += "            font-weight: bold; ";
  template += "        } ";
  template += "        span.title ";
  template += "{            font-size: 28pt; ";
  template += "        } ";
  template += "        span.number ";
  template += "{            font-size: 16pt; ";
  template += "        } ";
  template += "        span.itemname ";
  template += "{            font-weight: bold; ";
  template += "            line-height: 150%; ";
  template += "        } ";
  template += "        hr ";
  template += "{            width: 100%; ";
  template += "            color: #d3d3d3; ";
  template += "            background-color: #d3d3d3; ";
  template += "            height: 1px; ";
  template += "        } ";
  template += "</style> ";
  template += "</head> ";
  template += "  <#if record.entity.address?length lte 100> ";
  template += "    <body header=\"nlheader\" header-height=\"43%\" footer=\"nlfooter\" footer-height=\"8%\" padding=\"0in 0.3in 0in 0.3in\" size=\"A4\"> ";
  template += "         <#else> ";
  template += "    	<body header=\"nlheader\" header-height=\"47%\" footer=\"nlfooter\" footer-height=\"8%\" padding=\"0in 0.3in 0in 0.3in\" size=\"A4\"> ";
  template += "   </#if> ";
  //template += "<table><tr><td>TEST</td></tr></table>"
  template += "<#if record.item?has_content || record.time?has_content> ";


  template += "<table class=\"itemtable\" style=\"width: 100%; margin-top: 10px;border:1px solid #000000;font-size:10px;\">";
  template += "<thead> ";
  template += "     <tr> ";
  template += "<td align=\"center\" colspan=\"5\" style=\"border-bottom:solid 1px #000000;font-weight:bold;\">TS Date</td>";
  template += "<td align=\"center\" colspan=\"4\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">TS No.</td>";
  template += "<td align=\"center\" colspan=\"12\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Description</td>";
  template += "<td align=\"center\" colspan=\"4\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Unit</td>";
  template += "<td align=\"center\" colspan=\"5\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Unit Price </td>";
  template += "<td align=\"center\" colspan=\"5\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">&nbsp;&nbsp;&nbsp;&nbsp;Amount<br/>&nbsp;(Excl.of VAT)</td>";
  template += "<td align=\"center\" colspan=\"3\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">VAT %</td>";
  template += "<td align=\"center\" colspan=\"5\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">VAT Amount </td>";
  template += "<td align=\"center\" colspan=\"5\" style=\"border-left:solid 1px #000000;border-bottom:solid 1px #000000;font-weight:bold;\">Total Amount <br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(${record.currencysymbol})</td>";
  template += "      </tr> ";
  template += "   </thead> ";

  template += "<!-- start items --><#list record.time?reverse as time> ";

  //template += "</#if> ";
  template += "<#if time.apply?string == 'Yes'>";
  template += "  <tr> ";
  template += "     <#if time.rate == 0> ";
  template += "     <td colspan=\"5\" style=\"text-align:center;\">&nbsp;" ;
  template += "<br/><span style=\"text-align:center;\">&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "<#" ;
  template += "if time.custcol_ts_edate?has_content>&nbsp;" ;
  template += "</#" ;
  template += "if></span><br/>&nbsp;" ;
  template += "</td> ";
  template += " <#else> ";
  template += "   <td colspan=\"5\" style=\"text-align:center;\"><#" ;
  template += "if time.custcol_ts_sdate?string == \"\">${time.custcol_ts_sdate}<#else>${time.custcol_ts_sdate?string[\"d-MMM-yyyy\"]}</#if><br/>" ;
  template += "<#" ;
  template += "if time.custcol_ts_edate?string != \"\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To</#if><br/><#if time.custcol_ts_edate?string == \"\">${time.custcol_ts_edate}<#else>${time.custcol_ts_edate?string[\"d-MMM-yyyy\"]}</#if></td> ";
  template += "    </#if> ";
  template += "   <td colspan=\"4\" style=\"border-left:solid 1px #000000;\">${time.custcol_ts_number}</td> ";
  template += "    <#if time.rate == 0> ";
  template += "     <td colspan=\"12\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "     <td colspan=\"4\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "    <#else> ";
  template += "   <td colspan=\"12\" style=\"border-left:solid 1px #000000;\">${time.memo}</td> ";
  template += "   <td colspan=\"4\" style=\"border-left:solid 1px #000000;\">${time.custcol_ts_units}</td> ";
  template += "    </#" ;
  template += "if> ";
  template += "   <#if time.rate == 0> ";
  template += "      <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "      <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "<td align=\"right\" colspan=\"3\" style=\"border-left:solid 1px #000000;\">&nbsp;</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;</td>";
  template += "      <#else> ";
  template += "        <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${time.rate?string[\"#,##0.00\"]}</td> ";
  template += "        <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${time.amount?string[\"#,##0.00\"]}</td> ";
  template += "<td align=\"right\" colspan=\"3\" style=\"border-left:solid 1px #000000;\">${time.taxrate1}</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${time.tax1amt?string[\"#,##0.00\"]}</td>";
  template += "    <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${time.grossamt?string[\"#,##0.00\"]}</td>";
  template += "  </#" ;
  template += "if> ";
  template += "   </tr> ";
  template += "</#if> ";
  template += "	</#list><!-- end items --> ";
  template += "<#list record.item?reverse as item>";
  template += "  <tr> ";
  template += "     <#if item.rate == 0> ";
  template += "     <td colspan=\"5\" style=\"text-align:center;\">&nbsp;" ;
  template += "<br/><span style=\"text-align:center;\">&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "<#" ;
  template += "if item.custcol_ts_edate?has_content>&nbsp;" ;
  template += "</#" ;
  template += "if></span><br/>&nbsp;" ;
  template += "</td> ";
  template += " <#else> ";
  template += "   <td colspan=\"5\" style=\"text-align:center;\"><#" ;
  template += "if item.custcol_ts_sdate?string == \"\">${item.custcol_ts_sdate}<#else>${item.custcol_ts_sdate?string[\"d-MMM-yyyy\"]}</#if>&nbsp;" ;
  template += "<#" ;
  template += "if item.custcol_ts_edate?string != \"\">To</#if><br/><#if item.custcol_ts_edate?string == \"\">${item.custcol_ts_edate}<#else>${item.custcol_ts_edate?string[\"d-MMM-yyyy\"]}</#if></td> ";
  template += "    </#if> ";
  template += "   <td colspan=\"4\" style=\"border-left:solid 1px #000000;\">${item.custcol_ts_number}</td> ";
  template += "    <#if item.rate == 0> ";
  template += "     <td colspan=\"12\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "     <td colspan=\"4\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "    <#else> ";
  template += "   <td colspan=\"12\" style=\"border-left:solid 1px #000000;\">${item.description}</td> ";
  template += "   <td colspan=\"4\" style=\"border-left:solid 1px #000000;\">${item.custcol_ts_units}</td> ";
  template += "    </#" ;
  template += "if> ";
  template += "   <#if item.rate == 0> ";
  template += "      <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "      <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;" ;
  template += "</td> ";
  template += "<td align=\"right\" colspan=\"3\" style=\"border-left:solid 1px #000000;\">&nbsp;</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">&nbsp;</td>";
  template += "      <#else> ";
  template += "        <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${item.rate?string[\"#,##0.00\"]}</td> ";
  template += "        <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${item.amount?string[\"#,##0.00\"]}</td> ";
  template += "<td align=\"right\" colspan=\"3\" style=\"border-left:solid 1px #000000;\">${item.taxrate1}</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${item.tax1amt?string[\"#,##0.00\"]}</td>";
  template += "    <td align=\"right\" colspan=\"5\" style=\"border-left:solid 1px #000000;\">${item.grossamt?string[\"#,##0.00\"]}</td>";
  template += "  </#" ;
  template += "if> ";
  template += "   </tr> ";
  template += "	</#list><!-- end items --> ";
  template += "       <#if record.discountitem?has_content><tr> ";
  template += "<td align=\"left\" colspan=\"30\" style=\"padding:5px;border-top:solid 1px #000000;\">${record.custbody_discount_description}</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\">(${record.discounttotal?string})</td>";
  template += "<td align=\"right\" colspan=\"3\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\">5%</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\">${(taxAmt - record.taxtotal)?string[\"#,##0.00\"]}</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"padding:5px;border-left:solid 1px #000000;border-top:solid 1px #000000;\">(${(record.discounttotal - (taxAmt - record.taxtotal))?string})</td>";
  template += "   	   </tr></#if> ";
  template += "       <tr> ";
  template += "       <td align=\"left\" colspan=\"30\" style=\"padding:5px;border-top:solid 1px #000000;\"><b>Amount in words: <i>${record.currencysymbol} ${record.custbody_amount_into_words?capitalize}</i></b></td> ";
  template += "<td align=\"right\" colspan=\"5\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\"><b>${(record.subtotal + record.discounttotal)?string[\"#,##0.00\"]}</b></td>";
  template += "<td align=\"right\" colspan=\"3\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\">&nbsp;</td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\"><b>${record.taxtotal?string[\"#,##0.00\"]}</b></td>";
  template += "<td align=\"right\" colspan=\"5\" style=\"padding:5px;border-top:solid 1px #000000;border-left:solid 1px #000000;\"><b>${record.total?string[\"#,##0.00\"]}</b></td>";
  template += "       </tr> ";
  template += "       </table> ";
  template += "	   ";
  template += "</#" ;
  template += "if> ";
  template += "     <table style=\"width:100%;margin-top:10px;\"> ";
  template += "       <tr><td align=\"right\"><b>E. &#38;" ;
  template += "O.E.</b></td></tr> ";
  template += "    </table> ";
  template += "    <!--<table style=\"width:100%;\"> ";
  template += "      <#" ;
  template += "if record.custbody_bank_details?has_content><tr><td style=\"font-size:11px;width:25%;font-weight:bold;\">Please arrange payment to :</td><td style=\"font-size:11px;width:75%;font-weight:bold;\">${record.custbody_bank_details}</td></tr> ";
  template += "      <tr><td style=\"font-size:11px;width:25%;\">&nbsp;" ;
  template += "</td><td style=\"font-size:11px;width:75%;font-weight:bold;\">All bank transfer charges to be borne by customer</td> ";
  template += "     </tr></#" ;
  template += "if> ";
  template += "    </table>--> ";
  template += "    <table style=\"width:100%;\"> ";
  template += "     <tr><td style=\"line-height:75px;\">&nbsp;" ;
  template += "</td></tr> ";
  template += "     <tr><td style=\"font-weight:bold;\" align=\"left\">Company Stamp :</td><#" ;
  template += "if record.custbody_subsidiary_legal_name?has_content><td style=\"width:336px;font-weight:bold;\" align=\"right\">For ${record.custbody_subsidiary_legal_name}</td><#else><td style=\"width:336px;font-weight:bold;\" align=\"right\">For ${record.subsidiary.legalname}</td></#if></tr> ";
  template += "  </table> ";
  template += "   <table style=\"margin-top:3px;\"> ";
  template += "       <!--<tr><td style=\"width:336px;\" align=\"left\">Received By &nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += ": &nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "_________________________________<br /><br />Received Date : &nbsp;" ;
  template += "&nbsp;" ;
  template += "&nbsp;" ;
  template += "_________________________________ </td></tr>--> ";
  template += "       <tr><td style=\"width:75px;margin-top:5px;\" align=\"left\">Received By</td><td style=\"width:100px;margin-top:5px;\" align=\"left\"> : _________________________________</td></tr> ";
  template += "       <tr><td style=\"width:75px;margin-top:5px;\" align=\"left\">Received Date</td><td style=\"width:100px;margin-top:5px;\" align=\"left\"> : _________________________________</td></tr> ";
  template += "  </table> ";
  template += "  <table style=\"width:100%;\"> ";
  template += "    <tr><td colspan=\"3\" style=\"font-size:10px;\"><br /><br /></td><td>______________<br/>Prepared by</td><td>______________<br/>Approved by</td></tr> ";
  template += "  </table> ";
  template += "</body> ";
  template += "</pdf>" ;
  renderer.setTemplate(template);
  renderer.addRecord('record', invoice);
  var xml = renderer.renderToString();
  var file = nlapiXMLToPDF(xml);
  response.setContentType('PDF', 'Invoice_lh'+invoice.getFieldValue("id")+'.pdf', 'inline');
  response.write(file.getValue());*/
}